### ISSUE TITLE
Unable to cast vote

### ISSUE THREAD

**Issue by joantyry** [IBM/evote#28]
I did a local installation but I am unable to cast vote. Query all assets gives the following output:

0000 | { "ballotCreated": false, "firstName": "jfgkl", "lastName": "jgfkl", "registrarId": "7890", "type": "voter", "voterId": "0000" }

0001 | { "ballotCreated": false, "firstName": "fghjkl", "lastName": "fghjkl", "registrarId": "56789", "type": "voter", "voterId": "0001" }

**Comment by horeaporutiu** [comment]
@joantyry 

This is likely because the init function was not called.

Go down to Fabric Gateways -> Channels -> mychannel -> voterContract -> init (right click on init) -> submit transaction

<img width="437" alt="Screen Shot 2020-04-03 at 10 13 40 AM" src="https://user-images.githubusercontent.com/10428517/78387212-cb51cf00-7593-11ea-858b-99f163aa61d3.png">

**Comment by joantyry** [comment]
It worked thanks.
