### ISSUE TITLE
Protect casted vote

### ISSUE THREAD

**Issue by leog** [IBM/evote#30]
I was wondering how the app and the contract can be changed to protect what a voter chose but still enable anyone to check their vote was casted correctly.

**Comment by horeaporutiu** [comment]
@leog 

You can use the `queryByKey` function and pass in your voterId. One of the fields of the voter object is `ballotCast` which indicates if they have voted or not, and what was indicated on the ballot.

You could create access control attributes / smart contract logic so that only the voter with their ID can query their own voter Object.

There is an example of attribute-based access control here: https://github.com/IBM/fabric-contract-attribute-based-access-control
