### ISSUE TITLE
an identity for admin user app admin does not exist in wallet

### ISSUE THREAD

**Issue by Krishna812** [IBM/evote#9]
When tried to register got an ERROR : an identity for admin user app admin does not exist in wallet. Run the enroll admin.js app before retrying. Kindly help me to resolve this

**Comment by ljbennett62** [comment]
@Krishna812 - how did you have the URL in your config.json file set up - it should look something like this:`"caName": "https://50.23.5.248:32087",`.  Note - you need the `https`. I ran into some similar and when I changed to use `https` - the enroll script worked.

**Comment by horeaporutiu** [comment]
@Krishna812 

Is this for the local or cloud instructions? If it is local, then make sure that you have exported the wallet into the `server` folder and make sure there are private and public keys in the wallet for the `admin` identity. If you are running on cloud, then make sure you have run `enrollAdmin.js` and that you see the identity for `app-admin` in your wallet in the `server` folder.

**Comment by Krishna812** [comment]
thanks a lot !!!
It worked for me

**Comment by Krishna812** [comment]
when i "query the world state", it shows the list of all voters registered. how can I reset the election so that I cannot see any previous inputs?

**Comment by horeaporutiu** [comment]
@Krishna812 

You could do one of the following:

Modify the [init](https://github.com/IBM/evote/blob/master/contract/lib/voterContract.js#L40) function to remove line 50 and 51 which create new voters. 

Or you could run the application as normal, and submit a [deleteMyAsset transaction](https://github.com/IBM/evote/blob/master/contract/lib/voterContract.js#L206) transaction through VSCode and then pass in the ID's of the voters which are on in the world state. So you would pass in `V1`, and `V2`, since the voterIDs that are created in the `init` function are V1 and V2.
